source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "money-rails", "~> 1.15"
gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
